name: Operator Build
description: Build an operator

inputs:
  image-name:
    description: Image name
    required: true
  docker-username:
    description: Docker username
    required: false
    default: ""
  docker-password:
    description: Docker password
    required: false
    default: ""

runs:
  using: "composite"
  steps:
  - name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v3
  - name: Login to DockerHub
    if: inputs.docker-username != '' && inputs.docker-password != ''
    uses: docker/login-action@v3
    with:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
  - name: Metadata
    id: metadata
    uses: docker/metadata-action@v5
    with:
      images: ${{ inputs.image-name }}
      tags: |
        type=semver,pattern=v{{major}}.{{minor}}.{{patch}}
        type=semver,pattern=v{{major}}.{{minor}}
        type=semver,pattern=v{{major}}
        type=ref,event=branch
        type=ref,event=pr
        type=sha,format=long,prefix=

  - name: Build and push
    uses: docker/build-push-action@v5
    with:
      tags: |
        ${{ steps.metadata.outputs.tags }}
      push: true
      context: .
