name: Docker Build
description: Build a Docker image and push it to a container registry

inputs:
  image-names:
    description: Image names
    required: true
  extra-tags:
    description: Extra tags
    required: false
    default: ""
  docker-username:
    description: Docker username
    required: false
    default: ""
  docker-password:
    description: Docker password
    required: false
    default: ""

outputs:
  image-names:
    description: Image names
    value: ${{ steps.metadata.outputs.images }}
  tags:
    description: Tags
    value: ${{ steps.metadata.outputs.tags }}

runs:
  using: "composite"
  steps:
  - name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v3
  - name: Login to DockerHub
    if: inputs.docker-username != '' && inputs.docker-password != ''
    uses: docker/login-action@v3
    with:
      username: ${{ inputs.docker-username }}
      password: ${{ inputs.docker-password }}
  - name: Create timestamp
    id: timestamp
    shell: bash
    run: echo timestamp=$(date -u +'%Y-%m-%dT%H:%M:%SZ') >> $GITHUB_OUTPUT
  - name: Metadata
    id: metadata
    uses: docker/metadata-action@v5
    with:
      images: |
        ${{ inputs.image-names }}
      tags: |
        type=semver,pattern=v{{major}}.{{minor}}.{{patch}}
        type=semver,pattern=v{{major}}.{{minor}}
        type=semver,pattern=v{{major}}
        type=ref,event=branch
        type=ref,event=pr
        type=sha,format=long,prefix=
        ${{ inputs.extra-tags }}

  - name: Build and push
    uses: docker/build-push-action@v5
    with:
      tags: |
        ${{ steps.metadata.outputs.tags }}
      annotations: |
        org.opencontainers.image.created=${{ steps.timestamp.outputs.timestamp }}
        org.opencontainers.image.source=https://github.com/${{ github.repository }}
        org.opencontainers.image.ref.name=${{ github.ref_name }}
      push: true
      context: .
      cache-from: type=gha
      cache-to: type=gha,mode=max
